processes:
  - name: worker1
    command: "python"
    args: 
      - "-c"
      - "import time, sys; print('arrancando worker1...'); time.sleep(2); print('terminado worker1'); sys.exit(0)"
    env:
      LOG_LEVEL: "debug"
      APP_ENV: "dev"
    working_dir: "."
    restart_policy: always
    backoff:
      base: 1s
      factor: 2.0
      max: 8s
      max_tries: 5
    
  - name: failer
    command: "python"
    args: 
      - "-c"
      - "import sys, time; print('arrancando failer...'); time.sleep(1); print('voy a fallar'); sys.exit(1)"
    env: {}
    working_dir: "."
    restart_policy: on-failure
    backoff:
      base: 500ms
      factor: 1.5
      max: 5s
      max_tries: -1 # -1 significa reintentos infinitos
